---
spring:
  config.activate.on-profile: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb?stringtype=unspecified
    username: postgres
    password: haechi
    hikari:
      maximum-pool-size: 30
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 79TqSEUqy2dldCBQxuvm8P84ipyxns3P1MmdanoEhnSODFEmSA

eth-node:
  url: https://tn.henesis.io/ethereum/goerli?clientId=815fcd01324b8f75818a755a72557750
---
spring:
  config.activate.on-profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: haechi
    hikari:
      maximum-pool-size: 50
  jpa:
    show-sql: false

jwt:
  secret: 79TqSEUqy2dldCBQxuvm8P84ipyxns3P1MmdanoEhnSODFEmSA

eth-node:
  url: https://tn.henesis.io/ethereum/goerli?clientId=815fcd01324b8f75818a755a72557750
---
spring:
  profiles:
    active: local